name: JLPT-Practice-Helper

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

env:
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  EMAIL_FROM: ${{ vars.EMAIL_FROM }}
  EMAIL_TO: ${{ vars.EMAIL_TO }}
  EMAIL_CC: ${{ vars.EMAIL_CC }}
  SMTP_HOST: ${{ vars.SMTP_HOST }}
  SMTP_PORT: ${{ vars.SMTP_PORT }}
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
  HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
  GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
  SUNO_API: ${{ secrets.SUNO_API }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Create out directory
      run: mkdir -p out

    - name: Build
      run: go build .

    - name: Run
      run: go run .

    - name: Save updated db files to this repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add static/data*
        git commit -m "Update db files for $(date +'%Y-%m-%d')"
        git push origin main

    - name: Checkout japanese-study-pages repository
      uses: actions/checkout@v2
      with:
        repository: DianaMaftei/japanese-study-pages
        token: ${{ secrets.JAPANESE_STUDY_PAGES_REPO_TOKEN }}
        path: target-repo

    - name: Copy generated file to target repo
      run: cp out/* target-repo/public/data/

    - name: Move daily generated lesson to japanese-study-pages repo
      working-directory: target-repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add public/data/*
        git commit -m "Add generated lesson for $(date +'%Y-%m-%d')"
        git push




