name: JLPT-Practice-Helper

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

env:
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  EMAIL_FROM: ${{ vars.EMAIL_FROM }}
  EMAIL_TO: ${{ vars.EMAIL_TO }}
  EMAIL_CC: ${{ vars.EMAIL_CC }}
  SMTP_HOST: ${{ vars.SMTP_HOST }}
  SMTP_PORT: ${{ vars.SMTP_PORT }}
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build .

    - name: Run
      run: go run .
